const initialValues = {
  title: '',
  streetAddress: '',
  zipCode: '',
  body: '',
  rentMonthly: '',
  securityDeposit: '',
  totalMoveInCost: '',
  otherFeesMonthly: '',
  housingType: '',
  roomPrivacy: '',
  moveInDate: '',
  numberOfCohabitants: '',
  hasPrivateBath: false,
  hasFurnishedRoom: false,
  hasParkingIncluded: false,
  hasWasherDryerInUnit: false,
  hasPetsAllowed: false,
  hasWifi: false,
  hasCableTelevision: false,
  hasKitchenAccess: false,
  hasPoolAccess: false,
  hasDrugTolerantCohabitants: false,
};

export default initialValues;
